# Generated by Django 4.0.4 on 2022-07-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='icon-services/')),
                ('name', models.CharField(max_length=40)),
                ('name_ar', models.CharField(max_length=40, null=True)),
                ('name_en', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(max_length=10000)),
                ('description_ar', models.TextField(max_length=10000, null=True)),
                ('description_en', models.TextField(max_length=10000, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_title_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('meta_description_ar', models.TextField(blank=True, max_length=500, null=True)),
                ('meta_description_en', models.TextField(blank=True, max_length=500, null=True)),
                ('keywords', models.TextField(blank=True, max_length=500)),
                ('keywords_ar', models.TextField(blank=True, max_length=500, null=True)),
                ('keywords_en', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
