# Generated by Django 4.0.4 on 2022-07-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxerp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
