# Generated by Django 4.0.4 on 2022-07-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doxerp', '0004_services_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='icon',
        ),
    ]
