# Generated by Django 4.0.4 on 2022-07-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxerp', '0005_remove_services_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='icon-solutions/')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=10000)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
