# Generated by Django 4.0.4 on 2022-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doxerp', '0006_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='description_ar',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='solutions',
            name='description_en',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='solutions',
            name='name_ar',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='solutions',
            name='name_en',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
