# Generated by Django 4.0.4 on 2022-07-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_description_blockquote_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_author',
        ),
    ]
