# Generated by Django 4.0.4 on 2022-07-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_image_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_detail_head',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_list',
        ),
    ]
