# Generated by Django 4.0.4 on 2022-07-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_image_detail_head_remove_post_image_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description_blockquote',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description_blockquote_ar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description_blockquote_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description_three',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description_three_ar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description_three_en',
        ),
    ]
