# Generated by Django 4.0.4 on 2022-07-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_clientlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlogo',
            name='description_ar',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='description_en',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='title_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientlogo',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
