# Generated by Django 4.0.4 on 2022-07-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_clientlogo_description_ar_clientlogo_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientlogo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clientlogo',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='clientlogo',
            name='description_en',
        ),
    ]
