# Generated by Django 4.0.4 on 2022-07-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_clientlogo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlogo',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='title_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
